from io import StringIO
import unittest
import blizzard

class TestWowTocParser(unittest.TestCase):
    def generateTestString(self, toc):
        testString = []

        testString.append(r'''toc = '\n'.join([''')
        testString.append('])')
        return '\n'.join(testString)

    def test_parseToc001(self):
        toc = '\n'.join([
            r'## Interface: 80000',
            r'## Title: Angry World Quests',
            r'## Notes: Adds World Quests to the quest list',
            r'## Author: Ermad',
            r'## SavedVariables: AngryWorldQuests_Config',
            r'## SavedVariablesPerCharacter: AngryWorldQuests_CharacterConfig',
            r'## X-Packaged-Version: v0.20.6',
            r'',
            r'Core.lua',
            r'',
            r'Config.lua',
            r'Locale.lua',
            r'',
            r'QuestFrame.lua',
            r'Data.lua'
        ])

        wtp = blizzard.WowTocParser(StringIO(toc))

        self.assertEqual(
            [wtp.getVersion(), wtp.getName(), wtp.getTocVersion()],
            ['v0.20.6','Angry World Quests','80000']
        )

    def test_parseToc002(self):
        toc = '\n'.join([
            r'#  --------------------',
            r'#  TellMeWhen',
            r'#  Originally by Nephthys of Hyjal <lieandswell@yahoo.com>',
            r'# ',
            r'#  Other contributions by:',
            r'''# 		Sweetmms of Blackrock, Oozebull of Twisting Nether, Oodyboo of Mug'thol,''',
            r'# 		Banjankri of Blackrock, Predeter of Proudmoore, Xenyr of Aszune',
            r'# '
            r'#  Currently maintained by'
            r'#  Cybeloras of Aerie Peak'
            r'#  --------------------'
            r'',
            r'',
            r'# Also dont forget to bump both of these - X-Interface is used to get the interface version in-game to check that the user is using a current client.',
            r'## Interface: 80300',
            r'# DONT FORGET TO TOC BUMP TELLMEWHEN_OPTIONS TOO!!',
            r'## X-Interface: 80300',
            r'## Title: TellMeWhen',
            r'## X-Curse-Project-ID: 8025',
            r'## X-WoWI-ID: 10855',
            r'',
            r'## Version: 8.7.4',
            r'## Author: Cybeloras of Aerie Peak',
            r'',
            r'## Notes: Provides visual, auditory, and textual notifications about cooldowns, buffs, and pretty much every other element of combat.',
            r'## Notes-zhCN: 为冷却、增益\减益及其他各个方面提供视觉、听觉以及文字上的通知。',
            r'## Notes-zhTW: 為冷卻、增益\減益及其他各個方面提供視覺、聽覺以及文字上的通知。',
            r'## Notes-deDE: Bietet visuelle, akustische und schriftliche Benachrichtigungen über Cooldowns, Buffs and so ziemlich alles andere.',
            r'## Notes-koKR: 재사용 대기, 강화 효과와 그밖의 꽤 많은 것에 관해 시청각적이고도 문자적인 알림을 제공합니다.',
            r'## Notes-ruRU: Визуальные, звуковые и текстовые оповещения о готовности заклинаний, способностей, наличии баффов\дебаффов и многого другого.',
            r'## Notes-esES: Proporciona notificaciones visuales, auditivas y textuales sobre tiempos de reutilización, ventajas y básicamente cualquier otra cosa. ',
            r'',
            r'## OptionalDeps: Masque, Ace3, OmniCC, tullaCC, sct, sctd, MikScrollingBattleText, Parrot, DRList-1.0, LibDogTag-3.0, LibDogTag-Unit-3.0, LibDogTag-Stats-3.0, LibSpellRange-1.0, LibOO-1.0, LibRangeCheck-2.0, LibBabble-CreatureType-3.0, LibBabble-Race-3.0, ElvUI, DBM-Core, BigWigs',
            r'# The per character settings are the old settings, but we still need them to upgrade to the new ones. If they aren\'t defined, then they will be deleted immediately',
            r'## SavedVariablesPerCharacter: TellMeWhen_Settings',
            r'## SavedVariables: TellMeWhenDB',
            r'## X-Embeds: LibStub, Ace3, LibSharedMedia-3.0, LibDataBroker-1.1, DRList-1.0, LibDogTag-3.0, LibDogTag-Unit-3.0, LibDogTag-Stats-3.0, LibSpellRange-1.0, LibOO-1.0, LibRangeCheck-2.0, LibBabble-CreatureType-3.0, LibBabble-Race-3.0',
            r'## X-Category: Combat',
            r'',
            r'Lib\LibStub\LibStub.lua',
            r'Lib\CallbackHandler-1.0\CallbackHandler-1.0.xml',
            r'Lib\LibOO-1.0\lib.xml',
            r'Lib\AceAddon-3.0\AceAddon-3.0.xml',
            r'Lib\AceConsole-3.0\AceConsole-3.0.xml',
            r'Lib\AceEvent-3.0\AceEvent-3.0.xml',
            r'Lib\AceTimer-3.0\AceTimer-3.0.xml',
            r'Lib\AceLocale-3.0\AceLocale-3.0.xml',
            r'Lib\AceDB-3.0\AceDB-3.0.xml',
            r'Lib\AceComm-3.0\AceComm-3.0.xml',
            r'Lib\AceSerializer-3.0\AceSerializer-3.0.xml',
            r'Lib\LibSharedMedia-3.0\lib.xml',
            r'Lib\libdatabroker-1-1\LibDataBroker-1.1.lua',
            r'',
            r'# DRList-1.0 uses an unconventional folder layout, requiring the double nesting.',
            r'Lib\DRList-1.0\DRList-1.0\DRList-1.0.xml',
            r'',
            r'Lib\LibDogTag-3.0\lib.xml',
            r'Lib\LibDogTag-Unit-3.0\lib.xml',
            r'Lib\LibDogTag-Stats-3.0\lib.xml',
            r'Lib\LibSpellRange-1.0\lib.xml',
            r'Lib\LibRangeCheck-2.0\LibRangeCheck-2.0.lua',
            r'Lib\LibBabble-CreatureType-3.0\lib.xml',
            r'Lib\LibBabble-Race-3.0\lib.xml',
            r'',
            r'Localization\TellMeWhen-enUS.lua',
            r'#Localization\TellMeWhen-deDE.lua',
            r'Localization\TellMeWhen-esES.lua',
            r'#Localization\TellMeWhen-esMX.lua',
            r'#Localization\TellMeWhen-frFR.lua',
            r'#Localization\TellMeWhen-koKR.lua',
            r'Localization\TellMeWhen-ruRU.lua',
            r'Localization\TellMeWhen-zhCN.lua',
            r'Localization\TellMeWhen-zhTW.lua',
            r'#Localization\TellMeWhen-ptBR.lua',
            r'#Localization\TellMeWhen-itIT.lua',
            r'Localization\StaticFormats.lua',
            r'',
            r'',
            r'TellMeWhen.lua',
            r'',
            r'',
            r'# Components\includes.core.xml',
            r'',
            r'# Components\Core\includes.core.xml',
            r'Components\Core\Utils.lua',
            r'',
            r'# Components\Core\BaseClasses\includes.core.xml',
            r'Components\Core\BaseClasses\GenericComponentImplementor.lua',
            r'Components\Core\BaseClasses\GenericModuleImplementor.lua',
            r'Components\Core\BaseClasses\GenericComponent.lua',
            r'Components\Core\BaseClasses\IconComponent.lua',
            r'Components\Core\BaseClasses\GroupComponent.lua',
            r'Components\Core\BaseClasses\ObjectModule.lua',
            r'Components\Core\BaseClasses\IconDataProcessorComponent.lua',
            r'',
            r'# Components\Core\Help\includes.core.xml',
            r'',
            r'# Components\Core\Spells\includes.core.xml',
            r'Components\Core\Spells\Equivalencies.lua',
            r'Components\Core\Spells\Spells.lua',
            r'Components\Core\Spells\AuraCache.lua',
            r'Components\Core\Spells\ClassSpellCache.lua',
            r'',
            r'# Components\Core\Suggester\includes.core.xml',
            r'',
            r'# Components\Core\Common\includes.core.xml',
            r'Components\Core\Common\Textures.lua',
            r'Components\Core\Common\SwingTimerMonitor.lua',
            r'Components\Core\Common\UpdateTableManager.lua',
            r'Components\Core\Common\PlayerNames.lua',
            r'Components\Core\Common\Item.lua',
            r'',
            r'# Components\Core\Common\DogTags\includes.core.xml',
            r'Components\Core\Common\DogTags\DogTags.lua',
            r'',
            r'# Components\Core\Conditions\includes.core.xml',
            r'Components\Core\Conditions\Conditions.lua',
            r'Components\Core\Conditions\ConditionObject.lua',
            r'Components\Core\Conditions\ConditionObjectConstructor.lua',
            r'Components\Core\Conditions\UpdateEngine.lua',
            r'Components\Core\Conditions\ConditionCategory.lua',
            r'Components\Core\Conditions\Condition.lua',
            r'',
            r'# Components\Core\Conditions\Categories\includes.core.xml',
            r'Components\Core\Conditions\Categories\Resources.lua',
            r'Components\Core\Conditions\Categories\Spells.lua',
            r'Components\Core\Conditions\Categories\BuffsDebuffs.lua',
            r'Components\Core\Conditions\Categories\Talents.lua',
            r'Components\Core\Conditions\Categories\Location.lua',
            r'Components\Core\Conditions\Categories\PlayerAttributes.lua',
            r'Components\Core\Conditions\Categories\UnitAttributes.lua',
            r'Components\Core\Conditions\Categories\PlayerCombatStats.lua',
            r'Components\Core\Conditions\Categories\Currencies.lua',
            r'Components\Core\Conditions\Categories\BossMods.lua',
            r'Components\Core\Conditions\Categories\Misc.lua',
            r'',
            r'# Components\Core\Units\includes.core.xml',
            r'Components\Core\Units\Units.lua',
            r'',
            r'# Components\Core\IconEvents\includes.core.xml',
            r'Components\Core\IconEvents\EventHandler.lua',
            r'',
            r'# Components\Core\Resizer_Generic\includes.core.xml',
            r'',
            r'# Components\Core\Snippets\includes.core.xml',
            r'Components\Core\Snippets\Snippets.lua',
            r'Components\Core\IconType.lua',
            r'Components\Core\IconView.lua',
            r'Components\Core\Group.lua',
            r'Components\Core\GroupModule.lua',
            r'Components\Core\Icon.lua',
            r'Components\Core\IconModule.lua',
            r'Components\Core\IconDataProcessor.lua',
            r'Components\Core\IconDataProcessorHook.lua',
            r'Components\Core\IconDataProcessors.lua',
            r'',
            r'# Components\EventHandlers\includes.core.xml',
            r'',
            r'# Components\EventHandlers\Sound\includes.core.xml',
            r'Components\EventHandlers\Sound\Sound.lua',
            r'',
            r'# Components\EventHandlers\Announcements\includes.core.xml',
            r'Components\EventHandlers\Announcements\Announcements.lua',
            r'',
            r'# Components\EventHandlers\Animations\includes.core.xml',
            r'Components\EventHandlers\Animations\Animations.lua',
            r'',
            r'# Components\EventHandlers\Counter\includes.core.xml',
            r'Components\EventHandlers\Counter\Counter.lua',
            r'',
            r'# Components\EventHandlers\Timer\includes.core.xml',
            r'Components\EventHandlers\Timer\Timer.lua',
            r'',
            r'# Components\EventHandlers\Lua\includes.core.xml',
            r'Components\EventHandlers\Lua\Lua.lua',
            r'',
            r'# Components\IconDataProcessorHooks\includes.core.xml',
            r'Components\IconDataProcessorHooks\IconDataProcessorHook_Alpha_ConditionReq\Alpha_ConditionReq.lua',
            r'Components\IconDataProcessorHooks\IconDataProcessorHook_Alpha_DurationReq\Alpha_DurationReq.lua',
            r'Components\IconDataProcessorHooks\IconDataProcessorHook_Alpha_StackReq\Alpha_StackReq.lua',
            r'Components\IconDataProcessorHooks\IconDataProcessorHook_Texture_CustomTex\Texture_CustomTex.lua',
            r'',
            r'# Components\GroupModules\includes.core.xml',
            r'Components\GroupModules\GroupModule_BaseConfig\module.lua',
            r'Components\GroupModules\GroupModule_GroupPosition\module.lua',
            r'Components\GroupModules\GroupModule_IconPosition\module.lua',
            r'Components\GroupModules\GroupModule_IconPosition_Sortable\module.lua',
            r'Components\GroupModules\GroupModule_Alpha\module.lua',
            r'',
            r'# Components\IconModules\includes.core.xml',
            r'Components\IconModules\IconModule_Self\Self.lua',
            r'Components\IconModules\IconModule_Alpha\Alpha.lua',
            r'Components\IconModules\IconModule_CooldownSweep\CooldownSweep.lua',
            r'Components\IconModules\IconModule_IconContainer\IconContainer.lua',
            r'Components\IconModules\IconModule_IconContainer_Masque\IconContainer_Masque.lua',
            r'Components\IconModules\IconModule_IconEventClickHandler\IconEventClickHandler.lua',
            r'Components\IconModules\IconModule_IconEventConditionHandler\IconEventConditionHandler.lua',
            r'Components\IconModules\IconModule_PowerBar\PowerBar.lua',
            r'Components\IconModules\IconModule_PowerBar_Overlay\PowerBar_Overlay.lua',
            r'Components\IconModules\IconModule_Texts\Texts.lua',
            r'Components\IconModules\IconModule_Backdrop\Backdrop.lua',
            r'Components\IconModules\IconModule_Texture\Texture.lua',
            r'Components\IconModules\IconModule_Texture_Colored\Texture_Colored.lua',
            r'Components\IconModules\IconModule_TimerBar\TimerBar.lua',
            r'Components\IconModules\IconModule_TimerBar_BarDisplay\TimerBar_BarDisplay.lua',
            r'Components\IconModules\IconModule_TimerBar_Overlay\TimerBar_Overlay.lua',
            r'',
            r'# Components\IconViews\includes.core.xml',
            r'Components\IconViews\Icon\Icon.lua',
            r'Components\IconViews\Bar\Bar.lua',
            r'Components\IconViews\BarV\BarV.lua',
            r'',
            r'# Components\IconTypes\includes.core.xml',
            r'Components\IconTypes\IconType_buff\buff.lua',
            r'Components\IconTypes\IconType_buffcheck\buffcheck.lua',
            r'Components\IconTypes\IconType_cast\cast.lua',
            r'Components\IconTypes\IconType_cleu\cleu.lua',
            r'Components\IconTypes\IconType_conditionicon\conditionicon.lua',
            r'Components\IconTypes\IconType_cooldown\cooldown.lua',
            r'Components\IconTypes\IconType_default\default.lua',
            r'Components\IconTypes\IconType_dotwatch\dotwatch.lua',
            r'Components\IconTypes\IconType_dr\dr.lua',
            r'Components\IconTypes\IconType_guardian\guardian.lua',
            r'Components\IconTypes\IconType_icd\icd.lua',
            r'Components\IconTypes\IconType_item\item.lua',
            r'Components\IconTypes\IconType_losecontrol\losecontrol.lua',
            r'Components\IconTypes\IconType_meta\meta.lua',
            r'Components\IconTypes\IconType_reactive\reactive.lua',
            r'Components\IconTypes\IconType_runes\runes.lua',
            r'Components\IconTypes\IconType_swingtimer\swingtimer.lua',
            r'Components\IconTypes\IconType_totem\totem.lua',
            r'Components\IconTypes\IconType_uierror\uierror.lua',
            r'Components\IconTypes\IconType_unitcooldown\unitcooldown.lua',
            r'Components\IconTypes\IconType_unitcondition\unitcondition.lua',
            r'Components\IconTypes\IconType_value\value.lua',
            r'Components\IconTypes\IconType_wpnenchant\wpnenchant.lua',
            r'',
            r'LDB.lua',
            r'',
            r'TellMeWhen.xml'
        ])

        wtp = blizzard.WowTocParser(StringIO(toc))

        self.assertEqual(
            [wtp.getVersion(), wtp.getName(), wtp.getTocVersion()],
            ['8.7.4','TellMeWhen','80300']
        )